2-setup_a_domain_name

diff --git a/web_server/1-install_nginx_web_server b/web_server/1-install_nginx_web_server
--- a/web_server/1-install_nginx_web_server
+++ b/web_server/1-install_nginx_web_server
@@ -1,17 +1,40 @@
 #!/usr/bin/env bash
-# installing and config nginx
+# Script that install nginx server and write content to the root.
+sudo apt update -y
+sudo apt install nginx -y
+sudo echo "Holberton School" > /var/www/html/index.html
+sudo service nginx restart
 
-apt-get update
-apt-get -y install nginx
 
-# adding an html page
-echo "Holberton School" > /var/www/html/index.html
+# This is another way of doing this challenge by writing the content directly to the the default index.html
+# sudo apt-get -y update && \
+# sudo apt-get -y install nginx
+# if [ $? -eq 0 ];
+# then
+#     sudo chown -R $USER:$USER /etc/nginx/nginx.conf
+#     sudo echo -e \
+#     "http {
+#         server {
+#             listen 80;
+#             location / {
+#                 root /var/www/wube.site
+#             }
+#         }
+#     }" > /etc/nginx/nginx.conf
+#    sudo mkdir -p /var/www/wube.site
+#    sudo chown -R $USER:$USER /var/www/wube.site
+#    sudo echo "Holberton School" > /var/www/wube.site/index.html
 
-# checking if service is running
-state=$(pgrep nginx)
-if [ -n "$state" ];
-then
-	sudo service nginx start
-else
-	sudo service nginx restart
-fi
+#     sudo service nginx start
+#     if [ $? -ne 0 ]
+#     then
+#         echo  "Can't start nginx"
+#         exit 1
+#     fi
+# else
+#     echo "Can't install nginx"
+#     exit 1
+# fi
+# echo "Holberton School"
+
+
